// AUTO-GENERATED by scripts/optimize-seminar-gallery.cjs — do not edit by hand.
export type GalleryPhoto = {
  id: string;
  thumb: string;
  full: string;
  width: number;
  height: number;
};

export const seminarPhotos: GalleryPhoto[] = [
  {
    "id": "01",
    "thumb": "/gallery/seminar-2025/thumb/01.webp",
    "full": "/gallery/seminar-2025/full/01.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "02",
    "thumb": "/gallery/seminar-2025/thumb/02.webp",
    "full": "/gallery/seminar-2025/full/02.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "03",
    "thumb": "/gallery/seminar-2025/thumb/03.webp",
    "full": "/gallery/seminar-2025/full/03.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "04",
    "thumb": "/gallery/seminar-2025/thumb/04.webp",
    "full": "/gallery/seminar-2025/full/04.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "05",
    "thumb": "/gallery/seminar-2025/thumb/05.webp",
    "full": "/gallery/seminar-2025/full/05.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "06",
    "thumb": "/gallery/seminar-2025/thumb/06.webp",
    "full": "/gallery/seminar-2025/full/06.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "07",
    "thumb": "/gallery/seminar-2025/thumb/07.webp",
    "full": "/gallery/seminar-2025/full/07.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "08",
    "thumb": "/gallery/seminar-2025/thumb/08.webp",
    "full": "/gallery/seminar-2025/full/08.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "09",
    "thumb": "/gallery/seminar-2025/thumb/09.webp",
    "full": "/gallery/seminar-2025/full/09.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "10",
    "thumb": "/gallery/seminar-2025/thumb/10.webp",
    "full": "/gallery/seminar-2025/full/10.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "11",
    "thumb": "/gallery/seminar-2025/thumb/11.webp",
    "full": "/gallery/seminar-2025/full/11.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "12",
    "thumb": "/gallery/seminar-2025/thumb/12.webp",
    "full": "/gallery/seminar-2025/full/12.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "13",
    "thumb": "/gallery/seminar-2025/thumb/13.webp",
    "full": "/gallery/seminar-2025/full/13.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "14",
    "thumb": "/gallery/seminar-2025/thumb/14.webp",
    "full": "/gallery/seminar-2025/full/14.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "15",
    "thumb": "/gallery/seminar-2025/thumb/15.webp",
    "full": "/gallery/seminar-2025/full/15.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "16",
    "thumb": "/gallery/seminar-2025/thumb/16.webp",
    "full": "/gallery/seminar-2025/full/16.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "17",
    "thumb": "/gallery/seminar-2025/thumb/17.webp",
    "full": "/gallery/seminar-2025/full/17.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "18",
    "thumb": "/gallery/seminar-2025/thumb/18.webp",
    "full": "/gallery/seminar-2025/full/18.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "19",
    "thumb": "/gallery/seminar-2025/thumb/19.webp",
    "full": "/gallery/seminar-2025/full/19.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "20",
    "thumb": "/gallery/seminar-2025/thumb/20.webp",
    "full": "/gallery/seminar-2025/full/20.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "21",
    "thumb": "/gallery/seminar-2025/thumb/21.webp",
    "full": "/gallery/seminar-2025/full/21.webp",
    "width": 2000,
    "height": 1333
  },
  {
    "id": "22",
    "thumb": "/gallery/seminar-2025/thumb/22.webp",
    "full": "/gallery/seminar-2025/full/22.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "23",
    "thumb": "/gallery/seminar-2025/thumb/23.webp",
    "full": "/gallery/seminar-2025/full/23.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "24",
    "thumb": "/gallery/seminar-2025/thumb/24.webp",
    "full": "/gallery/seminar-2025/full/24.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "25",
    "thumb": "/gallery/seminar-2025/thumb/25.webp",
    "full": "/gallery/seminar-2025/full/25.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "26",
    "thumb": "/gallery/seminar-2025/thumb/26.webp",
    "full": "/gallery/seminar-2025/full/26.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "27",
    "thumb": "/gallery/seminar-2025/thumb/27.webp",
    "full": "/gallery/seminar-2025/full/27.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "28",
    "thumb": "/gallery/seminar-2025/thumb/28.webp",
    "full": "/gallery/seminar-2025/full/28.webp",
    "width": 2000,
    "height": 1336
  },
  {
    "id": "29",
    "thumb": "/gallery/seminar-2025/thumb/29.webp",
    "full": "/gallery/seminar-2025/full/29.webp",
    "width": 2000,
    "height": 1336
  }
];
