// AUTO-GENERATED by scripts/optimize-gallery.cjs — do not edit by hand.
import type { GalleryPhoto } from "@/components/gallery/photo-gallery";

export const meetingPhotos: GalleryPhoto[] = [
  {
    "id": "01",
    "thumb": "/gallery/meetings-2026/thumb/01.webp",
    "full": "/gallery/meetings-2026/full/01.webp",
    "width": 2000,
    "height": 1500
  },
  {
    "id": "02",
    "thumb": "/gallery/meetings-2026/thumb/02.webp",
    "full": "/gallery/meetings-2026/full/02.webp",
    "width": 2000,
    "height": 1500
  },
  {
    "id": "03",
    "thumb": "/gallery/meetings-2026/thumb/03.webp",
    "full": "/gallery/meetings-2026/full/03.webp",
    "width": 1600,
    "height": 900
  },
  {
    "id": "04",
    "thumb": "/gallery/meetings-2026/thumb/04.webp",
    "full": "/gallery/meetings-2026/full/04.webp",
    "width": 2000,
    "height": 1126
  },
  {
    "id": "05",
    "thumb": "/gallery/meetings-2026/thumb/05.webp",
    "full": "/gallery/meetings-2026/full/05.webp",
    "width": 1600,
    "height": 900
  },
  {
    "id": "06",
    "thumb": "/gallery/meetings-2026/thumb/06.webp",
    "full": "/gallery/meetings-2026/full/06.webp",
    "width": 2000,
    "height": 1500
  },
  {
    "id": "07",
    "thumb": "/gallery/meetings-2026/thumb/07.webp",
    "full": "/gallery/meetings-2026/full/07.webp",
    "width": 1153,
    "height": 2048
  },
  {
    "id": "08",
    "thumb": "/gallery/meetings-2026/thumb/08.webp",
    "full": "/gallery/meetings-2026/full/08.webp",
    "width": 1200,
    "height": 1600
  },
  {
    "id": "09",
    "thumb": "/gallery/meetings-2026/thumb/09.webp",
    "full": "/gallery/meetings-2026/full/09.webp",
    "width": 1153,
    "height": 2048
  },
  {
    "id": "10",
    "thumb": "/gallery/meetings-2026/thumb/10.webp",
    "full": "/gallery/meetings-2026/full/10.webp",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "11",
    "thumb": "/gallery/meetings-2026/thumb/11.webp",
    "full": "/gallery/meetings-2026/full/11.webp",
    "width": 1600,
    "height": 1200
  },
  {
    "id": "12",
    "thumb": "/gallery/meetings-2026/thumb/12.webp",
    "full": "/gallery/meetings-2026/full/12.webp",
    "width": 1530,
    "height": 2040
  }
];
