/* eslint-disable */
// Generic gallery optimizer: turns a folder of photos (recursing into
// subfolders) into web-ready webp thumbnails + full images and emits a typed
// manifest. De-dupes by file *content* hash (filenames collide / repeat across
// WhatsApp exports, and same-named files are sometimes different images).
//
// Usage:
//   node scripts/optimize-gallery.cjs "<srcDir>" "<outName>" "<manifestPath>" "<exportVar>"
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const sharp = require("sharp");

const [, , SRC_DIR, OUT_NAME, MANIFEST_REL, EXPORT_VAR] = process.argv;
if (!SRC_DIR || !OUT_NAME || !MANIFEST_REL || !EXPORT_VAR) {
  console.error('Usage: node scripts/optimize-gallery.cjs "<srcDir>" "<outName>" "<manifestPath>" "<exportVar>"');
  process.exit(1);
}

const OUT_DIR = path.join(__dirname, "..", "public", "gallery", OUT_NAME);
const THUMB_DIR = path.join(OUT_DIR, "thumb");
const FULL_DIR = path.join(OUT_DIR, "full");
const MANIFEST = path.join(__dirname, "..", MANIFEST_REL);

const THUMB_WIDTH = 1000;
const FULL_WIDTH = 2000;

for (const d of [THUMB_DIR, FULL_DIR]) fs.mkdirSync(d, { recursive: true });

// Recursively collect jpeg/png/webp source files.
function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(p));
    else if (/\.(jpe?g|png|webp)$/i.test(entry.name)) out.push(p);
  }
  return out;
}

// De-dupe by content hash. Iterate in a deterministic (sorted-path) order so
// the kept copy is stable; then order the survivors by basename so the gallery
// reads chronologically (WhatsApp filenames embed the timestamp).
const all = walk(SRC_DIR).sort((a, b) => a.localeCompare(b));
const seen = new Set();
const unique = [];
for (const p of all) {
  const hash = crypto.createHash("sha1").update(fs.readFileSync(p)).digest("hex");
  if (seen.has(hash)) continue;
  seen.add(hash);
  unique.push(p);
}
unique.sort((a, b) => path.basename(a).localeCompare(path.basename(b)));

(async () => {
  const manifest = [];
  let i = 0;
  for (const srcPath of unique) {
    i += 1;
    const id = String(i).padStart(2, "0");
    const name = `${id}.webp`;

    const fullInfo = await sharp(srcPath)
      .rotate()
      .resize({ width: FULL_WIDTH, withoutEnlargement: true })
      .webp({ quality: 80 })
      .toFile(path.join(FULL_DIR, name));

    await sharp(srcPath)
      .rotate()
      .resize({ width: THUMB_WIDTH, withoutEnlargement: true })
      .webp({ quality: 78 })
      .toFile(path.join(THUMB_DIR, name));

    manifest.push({
      id,
      thumb: `/gallery/${OUT_NAME}/thumb/${name}`,
      full: `/gallery/${OUT_NAME}/full/${name}`,
      width: fullInfo.width,
      height: fullInfo.height,
    });
    console.log(`  ${id}  ${path.basename(srcPath)}  ->  ${fullInfo.width}x${fullInfo.height}`);
  }

  const ts = `// AUTO-GENERATED by scripts/optimize-gallery.cjs — do not edit by hand.
import type { GalleryPhoto } from "@/components/gallery/photo-gallery";

export const ${EXPORT_VAR}: GalleryPhoto[] = ${JSON.stringify(manifest, null, 2)};
`;
  fs.writeFileSync(MANIFEST, ts, "utf8");
  console.log(`\nDe-duped ${all.length} files -> ${manifest.length} unique photos -> ${MANIFEST}`);
})();
